### ISSUE TITLE
Installation problems, not only blum but others too

### ISSUE THREAD

**Issue by manasseh-zues** [vanhbakaa/Blum#12]
Traceback (most recent call last):
  File "C:\Users\nft_cyb0r9\blum\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\nft_cyb0r9\blum\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\nft_cyb0r9\blum\bot\utils\launcher.py", line 16, in <module>
    from bot.core.tapper import run_tapper, run_tapper1
  File "C:\Users\nft_cyb0r9\blum\bot\core\tapper.py", line 12, in <module>
    from aiocfscrape import CloudflareScraper
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nft_cyb0r9\blum\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by vanhbakaa** [comment]
use python 3.10-3.11.5
